spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INNER}/realms/${KEYCLOAK_REALM_NAME}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ${AUTHENTICATION_SERVICE_HOST}
              uri: lb://${AUTHENTICATION_SERVICE_HOST}
              predicates:
                - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${API_GATEWAY_PORT_INNER}
