spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST}:${KEYCLOAK_PORT_INNER}/realms/${KEYCLOAK_REALM_NAME}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ${AUTHENTICATION_SERVICE_HOST}
              uri: lb://${AUTHENTICATION_SERVICE_HOST}
              predicates:
                - Path=/auth/**
            - id: ${VACANCY_MANAGER_SERVICE_HOST}
              uri: lb://${VACANCY_MANAGER_SERVICE_HOST}
              predicates:
                - Path=/vacancy/**

token:
  refresh:
    cookie-lifetime: 30



api:
  authentication-service:
    token-refresh:
      path: http://${AUTHENTICATION_SERVICE_HOST}:${AUTHENTICATION_SERVICE_PORT_INNER}/auth/refresh
  nginx:
    host: ${NGINX_HOST}
    port: ${NGINX_PORT_INNER}

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${API_GATEWAY_PORT_INNER}
