spring:
  application:
    name: authentication-service

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

grpc:
  client:
    database-manager-grpc-service:
      address: discovery:///${DATABASE_MANAGER_HOST}
      negotiation-type: plaintext

keycloak:
  host: ${KEYCLOAK_HOST}
  port: ${KEYCLOAK_PORT_INNER}
  admin:
    username: ${KEYCLOAK_ADMIN_NAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
  realm:
    test:
      name: test
      client:
        id: authentication-service
      groups:
        - ROLES_DEFAULT
    master:
      name: master
      client:
        id: admin-cli

server:
  port: ${AUTHENTICATION_SERVICE_PORT_INNER}
