spring:
  application:
    name: authentication-service

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

grpc:
  client:
    database-manager-grpc-service:
      address: discovery:///${DATABASE_MANAGER_HOST}
      negotiation-type: plaintext

server:
  port: ${AUTHENTICATION_SERVICE_PORT}
