spring:
  application:
    name: vacancy-manager-service
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT_INNER}
      lifetime: 3600000
      hash_key: ${REDIS_HASH_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

api:
  hh:
    vacancies:
      uri: https://api.hh.ru/vacancies
    token:
      uri: https://api.hh.ru/token
  gigachat:
    token:
      uri: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    message:
      uri: https://gigachat.devices.sberbank.ru/api/v1/chat/completions

server:
  port: ${VACANCY_MANAGER_SERVICE_PORT}
